### ISSUE TITLE
Questions about the ablation study using PQ

### ISSUE THREAD

**Issue by LouisDo2108** [HansiZeng/RIPOR#5]
Hi @HansiZeng ,

I have a question regarding how you replace RQ with PQ in the ablation study. 
I find that you initialise the semantic tokens for RIPOR using centroids from RQ. 
In the case of PQ, since the centroids of PQ is much smaller in dimension, how do you initialise these tokens and what was the PQ setting?

Thank you.

**Comment by HansiZeng** [comment]
You can pad zeros to make PQ centroids into full-dimension.
For instance, assume you use PQ to initialize a DocID with 3 semantic tokens: $[c_1, c_2, c_3]$,
the corresponding centroids are:
c1: [.1, .2, .3]
c2: [.4,.5,.6]
c3: [.7,.8,.9]
If the full-dimension is 9, then you can pad zeros to these centroids:
c1: [.1, .2, .3, 0., 0., 0., 0., 0., 0.]
c2: [0., 0., 0., .4, .5, .6, 0., 0., 0.]
c3: [0., .0., 0., 0., 0., 0., .7, .8, .9]
